nodeLinker: node-modules
enableTransparentWorkspaces: false
enableConstraintsChecks: true
defaultSemverRangePrefix: "~"
injectEnvironmentFiles:
  - .env
npmScopes:
  genshi:
    npmRegistryServer: https://registry.npmjs.org
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_PAT}
