nodeLinker: node-modules
enableTransparentWorkspaces: false
enableConstraintsChecks: true
defaultSemverRangePrefix: "~"
injectEnvironmentFiles:
  - .env
# npmScopes:
#   hali:
#     npmRegistryServer: https://npm.pkg.github.com
#     npmAlwaysAuth: true
#     npmAuthToken: ${GITHUB_PAT}
