name: Package checks

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - ".vscode/*"
      - "README.md"
      - "LICENSE"
      - "CODE_OF_CONDUCT.md"

jobs:
  typecheck:
    name: "Typecheck"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: "docs"
      - shell: bash
        working-directory: "docs"
        run: yarn workspaces foreach -Ap run typecheck

  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: "docs"
      - shell: bash
        working-directory: "docs"
        run: yarn lint

  format:
    name: "Format"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: "docs"
      - shell: bash
        working-directory: "docs"
        run: yarn format

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: "docs"
      - shell: bash
        working-directory: "docs"
        run: yarn build
